import type { CharacterBlueprint } from "./character-blueprint"

export const DEFAULT_CHARACTER_BLUEPRINT: CharacterBlueprint = {
  character_metadata: {
    name_or_id: "",
    base_archetype: "",
    apparent_age: "",
    gender_presentation: "",
    ethnic_phenotype: [],
    body_type: "",
    overall_impression: "",
  },
  facial_anatomy: {
    bone_structure_and_proportions: {
      facial_thirds: "",
      face_shape: "",
      jawline: "",
      chin: "",
      cheekbones: "",
      forehead: "",
      temples: "",
      brow_ridge: "",
    },
    soft_tissue_and_flesh: {
      buccal_fat: "",
      nasolabial_folds: "",
      tear_troughs: "",
      submental_area: "",
      jowls: "",
    },
    skin_and_complexion: {
      base_tone: "",
      undertone: "",
      texture: "",
      identifying_marks: [],
      pigmentation_and_color_zones: {
        under_eyes: "",
        cheeks: "",
        mouth_area: "",
        forehead: "",
        veins: "",
      },
      aging_signs: {
        fine_lines: "",
        wrinkles: "",
        elasticity: "",
        sun_damage: "",
      },
    },
    asymmetries: {
      left_side_quirks: [],
      right_side_quirks: [],
      overall_symmetry: "",
    },
  },
  facial_features: {
    eyes: {
      shape: "",
      canthal_tilt: "",
      size: "",
      spacing: "",
      depth: "",
      eyelids: { upper: "", lower: "" },
      pupils: "",
      iris: { primary_color: "", secondary_color: "", pattern: "", limbal_ring: "" },
      sclera: "",
      tear_ducts: "",
      eyelashes: { upper: "", lower: "" },
    },
    eyebrows: {
      shape: "",
      thickness: "",
      texture: "",
      color: "",
      placement: "",
      grooming: "",
    },
    nose: {
      overall_size: "",
      bridge: "",
      tip: "",
      nostrils: "",
      septum: "",
      philtrum: "",
      dorsum_width: "",
    },
    mouth_and_lips: {
      overall_width: "",
      cupids_bow: "",
      upper_lip: "",
      lower_lip: "",
      lip_ratio: "",
      natural_color: "",
      texture: "",
      mouth_corners: "",
      internal_details: { gum_display: "", teeth_visibility: "" },
    },
    teeth: {
      incisors: "",
      canines: "",
      color: "",
      alignment: "",
      condition: "",
    },
    ears: {
      size: "",
      protrusion: "",
      lobes: "",
      shape: "",
      internal_cartilage: "",
    },
  },
  hair_and_pilosity: {
    head_hair: {
      base_color: "",
      highlights_and_undertones: "",
      texture: "",
      density: "",
      hairline: "",
      baby_hairs: "",
      styling: { parting: "", cut_and_length: "", current_state: "", volume_distribution: "" },
      condition: "",
    },
    facial_hair: {
      presence: "",
      pattern: "",
      texture_and_color: "",
      length: "",
    },
    upper_body_hair: {
      chest_and_abdomen: "",
      arms_and_hands: "",
      back_and_shoulders: "",
    },
  },
  torso_and_upper_body: {
    neck: { length: "", thickness: "", features: "", skin: "" },
    shoulders: { width: "", slope: "", collarbones: "", deltoid_definition: "" },
    chest: { build: "", bust_shape: "", sternum: "" },
    upper_back: { trapezius: "", scapula: "", spine_visibility: "" },
    torso_skin: { texture: "", identifying_marks: [] },
    posture_silhouette: "",
  },
  upper_limbs_and_hands: {
    arms: { thickness_and_tone: "", vascularity: "", skin_condition: "" },
    hands: { size: "", fingers: "", knuckles: "", palms_and_texture: "", wrist_bone: "" },
    nails: { shape: "", length: "", condition: "" },
  },
  body_modifications: {
    tattoos: [],
    piercings: { ears: [], face: [], mouth: [], body: [] },
    scars_and_branding: [],
    cosmetic_procedures: "",
  },
  expression_and_body_language: {
    default_resting_expression: "",
    facial_micro_movements: {
      forehead_tension: "",
      eye_engagement: "",
      mouth_tension: "",
      nose_movement: "",
      neck_and_jaw_tension: "",
    },
    posture_and_carriage: {
      spine: "",
      shoulder_carriage: "",
      head_tilt: "",
      hand_resting_position: "",
    },
    smile_description: "",
  },
  cosmetics_and_grooming: {
    skincare_finish: "",
    makeup: {
      base: "",
      contour_and_highlight: "",
      eyes: "",
      brows: "",
      lips: "",
      blush: "",
    },
    fragrance_vibe: "",
  },
  upper_body_styling: {
    clothing: {
      neckline: "",
      shoulder_fit: "",
      sleeve_length: "",
      fabric_details: "",
      fit: "",
      layering: "",
    },
    accessories: {
      ears: [],
      neck: [],
      wrists_and_hands: [],
      headwear: "",
      eyewear: "",
    },
  },
  character_consistency_anchors: {
    must_keep_traits: [],
    avoid_elements: [],
    signature_colors: [],
    lighting_notes: "",
  },
}
